import { Container } from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import PageHome from "./components/home";
import Nav from "./components/nav/nav";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <Nav />
      <Container>
        <PageHome />
      </Container>
    </div>
  );
}
